name: Android parte 01 - Core (AK/LibCore)

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v7.0.1

      - name: Compilar LibCore para arm64-v8a
        uses: ./.github/actions/android-part
        with:
          target: LibCore
